<?php
session_start();

// Handle form submission
if (isset($_POST['continue'])) {
    $selected_date = $_POST['selected_date'] ?? '';
    if ($selected_date != '') {
        $_SESSION['last_period_date'] = $selected_date;
        header("Location: 4congratulations.php");
        exit;
    } else {
        $error = "Please select a date before continuing.";
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Select Last Period</title>
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #ffeef2;
        display: flex;
        justify-content: center;
        align-items: flex-start;
        padding: 30px 10px;
        margin: 0;
        min-height: 100vh;
        color: #333;
    }
    .container { width: 100%; max-width: 450px; text-align: center; }
    .header { text-align: left; padding: 0 10px 20px; }
    .back-link { font-size: 16px; color: #666; text-decoration: none; display: flex; align-items: center; margin-bottom: 25px; }
    .back-link::before { content: '←'; margin-right: 8px; font-size: 20px; font-weight: bold; }
    h1 { font-size: 24px; font-weight: bold; color: #333; margin: 0; }
    .subtitle { font-size: 14px; color: #888; margin-top: 5px; font-weight: 500; }
    .main-card { background-color: white; padding: 20px; border-radius: 25px; box-shadow: 0 8px 20px rgba(255, 133, 162, 0.1); margin-bottom: 20px; }
    .calendar-container { width: 100%; max-width: 320px; margin: 0 auto; padding: 15px 0; }
    .calendar-header { display: flex; justify-content: space-between; align-items: center; font-size: 16px; font-weight: bold; margin-bottom: 15px; padding: 0 10px; }
    .calendar-header button { background: none; border: none; font-size: 20px; color: #ff69b4; cursor: pointer; padding: 5px; }
    .calendar-grid { display: grid; grid-template-columns: repeat(7, 1fr); gap: 5px; }
    .day-label { font-size: 12px; color: #999; font-weight: bold; text-align: center; padding: 8px 0; }
    .day-cell { font-size: 14px; color: #333; text-align: center; padding: 5px 0; width: 32px; height: 32px; line-height: 32px; margin: 0 auto; border-radius: 50%; cursor: pointer; transition: background-color 0.1s; }
    .day-cell.inactive { color: #ccc; cursor: default; }
    .day-cell.selected { background-color: #f7ccd5; color: #ff3377; font-weight: bold; border: 2px solid #ff3377; }
    .day-cell:not(.inactive):hover { background-color: #f0f0f0; }
    .selected-date-box { background-color: #ffe8ed; padding: 15px 20px; border-radius: 10px; margin-top: 20px; display:none; }
    .selected-date-box .label { font-size: 12px; color: #ff69b4; font-weight: bold; margin-bottom: 5px; }
    .selected-date-box .date { font-size: 20px; font-weight: bold; color: #333; }
    .continue-button { width: 100%; max-width: 450px; padding: 18px 0; margin-top: 30px; background-color: #ff69b4; color: white; font-size: 18px; font-weight: bold; border: none; border-radius: 12px; cursor: pointer; box-shadow: 0 4px 6px rgba(255, 105, 180, 0.3); transition: background-color 0.2s; }
    .continue-button:hover { background-color: #ff4d9a; }
    .error-msg { color: red; font-size: 14px; margin-top: 10px; }
</style>
</head>
<body>

<div class="container">
    <div class="header">
        <a href="2start_pregnancy.php" class="back-link">Back</a>
        <h1>Select Your Last Period</h1>
        <p class="subtitle">Choose the first day of your last menstrual period</p>
    </div>

    <form method="POST" action="">
        <div class="main-card">
            <div class="calendar-container">
                <div class="calendar-header">
                    <button type="button" id="prev">&lt;</button>
                    <span id="month-year"></span>
                    <button type="button" id="next">&gt;</button>
                </div>

                <div class="calendar-grid" id="calendar">
                    <!-- Calendar dynamically generated by JS -->
                </div>

                <div class="selected-date-box" id="selectedDateBox">
                    <div class="label">Selected Date</div>
                    <div class="date" id="selectedDateText"></div>
                </div>
            </div>
        </div>

        <input type="hidden" name="selected_date" id="hiddenSelectedDate">
        <button type="submit" name="continue" class="continue-button">Continue</button>
        <?php if (!empty($error)) echo '<div class="error-msg">'.$error.'</div>'; ?>
    </form>
</div>

<script>
const monthYear = document.getElementById('month-year');
const calendar = document.getElementById('calendar');
const selectedBox = document.getElementById('selectedDateBox');
const selectedText = document.getElementById('selectedDateText');
const hiddenInput = document.getElementById('hiddenSelectedDate');
const prevBtn = document.getElementById('prev');
const nextBtn = document.getElementById('next');

let currentDate = new Date(); // Start from current month/year

function renderCalendar(date) {
    const year = date.getFullYear();
    const month = date.getMonth();

    const firstDay = new Date(year, month, 1).getDay();
    const lastDate = new Date(year, month + 1, 0).getDate();

    const monthNames = [
        'January','February','March','April','May','June',
        'July','August','September','October','November','December'
    ];

    monthYear.textContent = `${monthNames[month]} ${year}`;

    let days = '';

    // Weekday labels
    const dayLabels = ['Su','Mo','Tu','We','Th','Fr','Sa'];
    dayLabels.forEach(label => {
        days += `<div class="day-label">${label}</div>`;
    });

    // Empty cells before start of month
    for (let i = 0; i < firstDay; i++) {
        days += `<div class="day-cell inactive"></div>`;
    }

    // Actual days
    for (let day = 1; day <= lastDate; day++) {
        days += `<div class="day-cell">${day}</div>`;
    }

    calendar.innerHTML = days;

    // Add click functionality for days
    document.querySelectorAll('.day-cell:not(.inactive)').forEach(cell => {
        cell.addEventListener('click', () => {
            document.querySelectorAll('.day-cell').forEach(c => c.classList.remove('selected'));
            cell.classList.add('selected');
            const fullDate = `${monthNames[month]} ${cell.textContent}, ${year}`;
            selectedText.textContent = fullDate;
            hiddenInput.value = fullDate;
            selectedBox.style.display = 'block';
        });
    });
}

prevBtn.addEventListener('click', () => {
    currentDate.setMonth(currentDate.getMonth() - 1);
    renderCalendar(currentDate);
});

nextBtn.addEventListener('click', () => {
    currentDate.setMonth(currentDate.getMonth() + 1);
    renderCalendar(currentDate);
});

// Initialize calendar
renderCalendar(currentDate);
</script>

</body>
</html>
